### ISSUE TITLE
Not enough Documentation

### ISSUE THREAD

**Issue by pradyunsg** [tridge/pyUblox#1]
Dear All,
  This seems to be a good project/bunch of code but it lacks documentation. So, a stranger like me can't really figure out how to use something like this. So, my humble request, Please document the code (at least with doc-strings)

**Comment by sorki** [comment]
+1 
Configuration functionality seems really useful.

**Comment by thijstriemstra** [comment]
+1 why is there not even a readme file?

**Comment by liutairan** [comment]
Great project, but really wish to have some documents. Thanks anyway.

**Comment by PythonCA** [comment]
I wish there is a Readme file. It seems a good module

**Comment by pradyunsg** [comment]
Closing because I don't expect anything... Feel free to open a new issue.
