### ISSUE TITLE
please identify a license

### ISSUE THREAD

**Issue by monkeypants** [tridge/pyUblox#8]
@tridge, I'd like to use your pyUblox module (on GitHub) in a project but would benefit from the clarity of a `LICENCE.txt`

GPLv3 would suit me fine, but really knowing where it stands is the main thing. Humbly request that you add one.

**Comment by monkeypants** [comment]
Doh, I see this in `ublox.py`
```
UBlox binary protocol handling
Copyright Andrew Tridgell, October 2012
Released under GNU GPL version 3 or later
```

**Comment by vazhnov** [comment]
I found link to the https://github.com/tridge/pyUblox/blob/master/RTCMv2.py from OSM wiki: https://wiki.openstreetmap.org/wiki/UbloxRAW

But there is no license information in `RTCMv2.py`.

@tridge , could you please add `LICENSE` file for whole repository?
It is easy to do with GitHub web-interface, there are ready templates for the most popular licenses.
